name: aandi_admin_api
description: Admin APIs package for AANDI admin service
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  aandi_api_protocol:
    path: ../api_protocol
  aandi_auth:
    path: ../auth
  http: ^1.2.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  dio: ^5.9.2
  flutter_test:
    sdk: flutter


dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^3.0.6
  json_serializable: ^6.9.0
  test: any
